/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nk.view;

public class VLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form IniciarSesion
     */
    public VLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgUser = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        rbAdministrador = new javax.swing.JRadioButton();
        rbCliente = new javax.swing.JRadioButton();
        rbEmpleado = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 620));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Iniciar Sesión");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 275, 53));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTRASEÑA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(250, 250, 250));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(10, 10, 10));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 210, 60));

        txtUser.setBackground(new java.awt.Color(33, 45, 62));
        txtUser.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(250, 250, 250));
        txtUser.setBorder(null);
        txtUser.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 40));

        txtPassword.setBackground(new java.awt.Color(33, 45, 62));
        txtPassword.setFont(txtPassword.getFont().deriveFont(txtPassword.getFont().getSize()+7f));
        txtPassword.setForeground(new java.awt.Color(250, 250, 250));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 270, 36));

        jSeparator1.setBackground(new java.awt.Color(207, 10, 10));
        jSeparator1.setForeground(new java.awt.Color(220, 95, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 10));

        jSeparator2.setBackground(new java.awt.Color(207, 10, 10));
        jSeparator2.setForeground(new java.awt.Color(220, 95, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, 10));
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 48, 36));
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 48, 42));

        jCheckBox1.setBackground(new java.awt.Color(33, 45, 62));
        jCheckBox1.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Recuérdame");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, -1));

        bgUser.add(rbAdministrador);
        rbAdministrador.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        rbAdministrador.setForeground(new java.awt.Color(250, 250, 250));
        rbAdministrador.setText("Administrador");
        rbAdministrador.setOpaque(false);
        jPanel2.add(rbAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 120, -1));

        bgUser.add(rbCliente);
        rbCliente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        rbCliente.setForeground(new java.awt.Color(250, 250, 250));
        rbCliente.setText("Cliente");
        rbCliente.setOpaque(false);
        jPanel2.add(rbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 90, -1));

        bgUser.add(rbEmpleado);
        rbEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        rbEmpleado.setForeground(new java.awt.Color(250, 250, 250));
        rbEmpleado.setText("Empleado");
        rbEmpleado.setOpaque(false);
        rbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(rbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 90, -1));

        btnLogin.setBackground(new java.awt.Color(33, 45, 62));
        btnLogin.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ingresar");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.setFocusable(false);
        btnLogin.setOpaque(true);
        btnLogin.setRequestFocusEnabled(false);
        btnLogin.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 210, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgUser;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblUser;
    public javax.swing.JRadioButton rbAdministrador;
    public javax.swing.JRadioButton rbCliente;
    public javax.swing.JRadioButton rbEmpleado;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
